name: my_debounce
description: Exactly what you are thinking about - debouncing a function call
version: 0.1.1
homepage: https://github.com/krasimir/debounce

environment:
  sdk: ">=2.8.0 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.15.4
